source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'

gem "devise"
gem "cancan"
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'

group :development, :test do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem "rspec"
  gem "rspec-rails"
end

group :test do
  gem "cucumber"
  gem "cucumber-rails"
  gem "capybara"
  gem "launchy"
end

