source 'http://rubygems.org'

gem 'rails', '3.0.6'

gem 'sqlite3'


gem "devise"
gem "cancan"
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'

gem 'unicorn'

group :development, :test do
  gem 'ruby-debug19', :require => 'ruby-debug'
end

group :test do
  gem "cucumber"
  gem "cucumber-rails"
end

