# OAuth
vkontakte_key: "6654993"
vkontakte_secret: "PzzKnV5LeLIEPdhtAdQ6"
yandex_key: "b8c1e93a67e64d90af8e7c69d1fdb725"
yandex_private_key: "f266fc74610944449b076aa1a3650dd7"
google_client_id: "649101184785-851hpg9hb40vthc38u9affenebis4tou.apps.googleusercontent.com"
google_client_secret: "Ho5NSfEGH4Lz9gs9HYHvWWtY"